# Generated by Django 5.0.3 on 2024-10-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_city_services_state_location_city_states'),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='configurations.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='configurations.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='offline_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='online_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='services',
            field=models.ManyToManyField(related_name='listings', to='configurations.services'),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='configurations.state'),
            preserve_default=False,
        ),
    ]
