# Generated by Django 5.0.3 on 2024-10-04 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_degree_memberships_registration_specialization_and_more'),
        ('listing', '0002_listing_city_listing_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='listing/banner_images'),
        ),
        migrations.AddField(
            model_name='listing',
            name='claimed',
            field=models.BooleanField(default=False, verbose_name='Profile Claimed'),
        ),
        migrations.AddField(
            model_name='listing',
            name='experienceyear',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='memberships',
            field=models.ManyToManyField(related_name='listings', to='configurations.memberships'),
        ),
        migrations.AddField(
            model_name='listing',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='listing/profile_images'),
        ),
        migrations.AddField(
            model_name='listing',
            name='qna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='specialization',
            field=models.ManyToManyField(related_name='listings', to='configurations.specialization'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='educations', to='configurations.city')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='educations', to='configurations.college')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='educations', to='configurations.degree')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='educations', to='configurations.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='education',
            field=models.ManyToManyField(related_name='listings', to='listing.education'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='experience',
            field=models.ManyToManyField(related_name='listings', to='listing.experience'),
        ),
        migrations.CreateModel(
            name='RegistrationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrations', to='configurations.registration')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='registration',
            field=models.ManyToManyField(related_name='listings', to='listing.registrationlist'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training', to='configurations.city')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training', to='configurations.college')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training', to='configurations.degree')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training', to='configurations.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
